### ISSUE TITLE
nvcc is present in AMD64 ros-torch:noetic-desktop-full-torch2.1.0 image, but not in ARM one

### ISSUE THREAD

**Issue by antun** [ika-rwth-aachen/docker-ros-ml-images#16]
**BACKGROUND**
I'm currently using the ros-torch:noetic-desktop-full-torch2.1.0 image because it's has ROS+CUDA preinstalled as well as being a multi-architecture image. So far I've only had it running successfully on AMD64 (Intel) hardware, and am trying to use it on ARM hardware. On the ARM image, as part of my build, cmake is throwing errors about not being able to find CUDA. So I tried to run `nvcc --version` on the ARM build and found it wasn't there.

**STEPS**
1. On an AMD64 machine, run`docker image pull rwthika/ros-torch:noetic-desktop-full-torch2.1.0` to get the latest image
2. Start up a container: `docker run -it --rm rwthika/ros-torch:noetic-desktop-full-torch2.1.0`
3. Run `nvcc --version` - you get valid output:

```
root@b50b900aea99:/docker-ros/ws# nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jul_14_19:41:19_PDT_2021
Cuda compilation tools, release 11.4, V11.4.100
Build cuda_11.4.r11.4/compiler.30188945_0
```

`which nvcc` shows: `/usr/local/cuda/bin/nvcc`

4. Now repeat steps 1-3 on an ARM64 host.

**RESULT**
On the ARM host, I get:

```
bash: nvcc: command not found
```

**EXPECTED**
I would expect both images to have similar contents.

**NOTES**
I noticed on the Docker hub page that there was a big difference in image size: https://hub.docker.com/layers/rwthika/ros-torch/noetic-desktop-full-torch2.1.0/images/sha256-e98452925fa557ee164e5511459629f3d8e1160f06b9b39b65c84486d6ab1fbf

linux/amd64 -> 9.19GB
linux/arm64 -> 3.2GB

**Comment by lreiher** [comment]
For the `ros-torch:noetic` images, we are using these two images as base images:
- amd64: [`nvcr.io/nvidia/tensorrt:21.08-py3 AS base-tensorrt-ubuntu20.04-amd64`](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/Dockerfile#L40)
- arm64: [`nvcr.io/nvidia/l4t-tensorrt:r8.5.2-runtime AS base-tensorrt-ubuntu20.04-arm64`](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/Dockerfile#L44)

Note that the arm64 variant (optimized for L4T NVIDIA Jetson devices) is explicitly set to `runtime`, i.e., it does not include developer tools such as the CUDA compiler `nvcc`. For amd64, NVIDIA does not offer `devel` and `runtime` versions, that's why the amd64 image is larger and does include `nvcc`.

Nevertheless, CUDA is indeed installed in both amd64 and arm64 images. I just checked again, you can find CUDA at `/usr/local/cuda-11.4` in the arm64 image. If you only need to use CUDA (e.g., when just using PyTorch to run inference), then you should be good to go. If you require `nvcc`, you need to manually install the CUDA developer tools.

That being said, note that we are not going to maintain these images much longer, as ROS 1 Noetic is set to go end-of-life in May 2025. You should consider switching to ROS 2.

**Comment by antun** [comment]
Thanks for the explanation.

For anyone else running into this, I was able to install the CUDA developer tools in my Dockerfile by adding:

```
ARG BUILD_ARCH
RUN if [ $BUILD_ARCH = "arm64v8" ]; then \
        apt-get update && \
        apt-get install -y cuda-toolkit-11-4 && \
        rm -rf /var/lib/apt/lists/* \
    ; fi
```

... and running `docker build` with a `--build-arg BUILD_ARCH= arm64v8`.

Also, I understand that ROS 1 is older - it's just what we're on currently.
