### ISSUE TITLE
Cannot find cuda toolkit using rwthika/ros2-cuda:foxy-desktop 

### ISSUE THREAD

**Issue by tiesus** [ika-rwth-aachen/docker-ros-ml-images#3]
Hi, 
 we use your docker contianers to develop our applications in it. 
One problem using the container is that the `nvcc --version` command is not found. The output of the command is: `bash: nvcc: command not found` </br> We start the container with: `docker run --gpus all -it --rm  rwthika/ros2-cuda:foxy-desktop tail -f /dev/null
`
</br>

The host is has an gpu (GTX-1650) and has the nvidia container toolkit installed. The  output of the nvcc -- version command on the host is: `nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
`

Can you explain how to solve the problem?

**Comment by lreiher** [comment]
First let me ask: are you sure that you need nvcc?

The reason that nvcc is missing is that we are only installing the CUDA runtime libraries into the images in order to optimize the image size. [This line](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/cuda/Dockerfile#L72) in the Dockerfile for the CUDA base images ([see README](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/cuda/README.md)) is explicitly only installing `cuda-libraries-*`, not `cuda-toolkit-*`. Same principle applies to the installation of cuDNN and TensorRT.

In order to install nvcc (and other development-related stuff), you would need to build your own Docker image. You can either ...
1. ... rebuild the CUDA base image with the optional build argument `INSTALL_AS_DEV=1` ([see here](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/cuda/README.md#build)), then rebuild the `ros2-cuda` image based on the new CUDA base image ([see here](https://github.com/ika-rwth-aachen/docker-ros-ml-images/blob/main/Dockerfile#L1)),
2. ... or simpler, create a new Dockerfile based on the existing `ros2-cuda` image and install `cuda-toolkit-*` on top of it.

**Comment by tiesus** [comment]
Thanks for your answer. We use your Dockerfiles as base image for our development environment based on this repo: https://github.com/athackst/vscode_ros2_workspace </br>

We have repositories which needs CUDA to build them. Therefore I think we need the `cuda toolkit` or am i wrong? </br>

I think with you explanations and the code example things are clearer for me and I can handle to install all stuff we need for our self. I was confused that for example images like `nvcr.io/nvidia/cuda:11.8.0-devel-ubuntu20.04` had the cuda toolkit installed and other images like `nvidia/cuda:11.8.0-runtime-ubuntu20.04` but with the seperation between devel and runtime image it's clear.

**Comment by lreiher** [comment]
Yes, if you need CUDA at build time you probably want to have the dev toolkit.

We chose to exclude it from our images as they easily grow large. Should be easy enough to just install it afterwards though.
